<template>
    <div class="universal-group">
        <div v-if="mainStore.phase<1">
            <div>
            <button disabled>save</button>
            </div>
            <div>
                <button disabled>export →</button>
            </div>
        </div>

        <div v-else>
            <div>
            <button>save</button>
            </div>
            <div>
                <button @click="exportFile" >export →</button>
            </div>
        </div>
    </div>
</template>


<script setup>
    import { useMainStore } from '../stores/MainStore'
    import { useSettingsStore } from '../stores/SettingsStore';

    const mainStore = useMainStore()
    const settingsStore = useSettingsStore(); 

    let rescale = 0.3521/1000;
    let approach = 0.1;
    let postScaler = 1000;

    function exportFile() {
        //let fso = CreateObject("Scripting.FileSystemObject");
        //let file = fso.CreateTextFile("../export.prg", True);
        var lines = "";

        let rapidSpeed = "[ 200, 500, 5000, 1000 ]";

        let lineCount = 0;

        lines += ("MODULE MOD_FeltCentral\n");
        lines += ("  PROC main()\n");                                                // main function
        lines += ("    ! Generated by Felt Central, © AATB GmbH, 2022\n");           // credits
        lines += ("    AccSet 20, 20;\n");                                           // accel/decel 20%
        lines += ("    ConfL \\Off;\n");                                             // disable IK wonkyness
        lines += ("    MoveAbsJ [[0,0,0,0,90,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + rapidSpeed + ",fine,calib,\\WObj:=table;\n"); // go home

        lineCount += 8;

        // loop through paths
        for (let i = 0; i < mainStore.rawPaths.length; i++) {

            if (mainStore.rawPaths[i] != null) {

                let x = mainStore.rawPaths[i][0][0] * rescale;
                let y = mainStore.rawPaths[i][0][1] * rescale;

                let feltingSpeed = "[ " + settingsStore.pathSettings[i].speedStart + ", 500, 5000, 1000 ]";

                //clamp to work area
                if (x < 0) x = 0;
                if (y < 0) y = 0;
                if (x > 1) x = 1.0;
                if (y > 1) y = 1.0;

                x *= postScaler;
                y *= postScaler;

                // go fast to first position down
                lines += ("    MoveL [[" + x + "," + y + ",-" + approach*postScaler + "],[1,0,0,0],[0,0,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + rapidSpeed + ",z1,calib,\\WObj:=table;\n");
                lines += ("    MoveL [[" + x + "," + y + ",0.000],[1,0,0,0],[0,0,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + rapidSpeed + ",z1,calib,\\WObj:=table;\n");
                lineCount += 2;

                // loop through points
                for (let j = 1; j < mainStore.rawPaths[i].length; j++) { // .length-1 ?

                    x = mainStore.rawPaths[i][j][0] * rescale;
                    y = mainStore.rawPaths[i][j][1] * rescale;

                    let speed = Number(settingsStore.pathSettings[i].speedStart);

                    if (settingsStore.pathSettings[i].speedStart != settingsStore.pathSettings[i].speedEnd) {
                        speed += Number(((settingsStore.pathSettings[i].speedEnd - settingsStore.pathSettings[i].speedStart) / mainStore.rawPaths[i].length) * j);
                        console.log(speed);
                    }

                    feltingSpeed = "[ " + speed + ", 500, 5000, 1000 ]";

                    // add speed changes here!

                    if (x < 0) x = 0;
                    if (y < 0) y = 0;
                    if (x > 1) x = 1.0;
                    if (y > 1) y = 1.0;

                    x *= postScaler;
                    y *= postScaler;

                    // slow felt until last position
                    lines += ("    MoveL [[" + x + "," + y + ",0.000],[1,0,0,0],[0,0,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + feltingSpeed + ",z1,calib,\\WObj:=table;\n");
                    lineCount++;
                }

                x = mainStore.rawPaths[i][mainStore.rawPaths[i].length-1][0] * rescale;
                y = mainStore.rawPaths[i][mainStore.rawPaths[i].length-1][1] * rescale;

                // add speed changes here!

                if (x < 0) x = 0;
                if (y < 0) y = 0;
                if (x > 1) x = 1.0;
                if (y > 1) y = 1.0;

                x *= postScaler;
                y *= postScaler;

                // go fast up
                lines += ("    MoveL [[" + x + "," + y + ",-" + approach*postScaler + "],[1,0,0,0],[0,0,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + rapidSpeed + ",z1,calib,\\WObj:=table;\n");
                lineCount++;
            }
        }

        // go above origin at the end of the file
        lines += ("    MoveAbsJ [[0,0,0,0,90,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]]," + rapidSpeed + ",fine,calib;\n");
        lines += ("  ENDPROC\n");
        lines += ("ENDMODULE");
        lineCount += 3;

        download("export.prg", lines);
    }

    function download(filename, text) {
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
        element.setAttribute('download', filename);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }

</script>


<style>
</style>